WebPortal/Models/ErrorViewModel.cs
namespace WebPortal.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebPortal/Models/Usuario.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebPortal.Models
{
    [Table("usuario")]

    public class Usuario
    {
        [Key]
        public int usuarioId { get; set; }

        [Required(ErrorMessage = "Nome deve ser informado!")]
        [StringLength(50, ErrorMessage = "Nome deve ter no maximo 50 caracteres!")]
        [Display(Name = "Nome")]
        public string usuarioNome { get; set; }

        [Required(ErrorMessage = "Nome deve ser informado!")]
        [StringLength(50, ErrorMessage = "Nome deve ter no maximo 50 caracteres!")]
        [Display(Name = "Sobrenome")]
        public string usuarioSobrenome { get; set; }

        [Display(Name = "Telefone")]
        [Required(ErrorMessage = "Telefone deve ser informado!")]
        [RegularExpression(@"^(?:(?:+|00)?(55)\s?)?(?:(?([1-9][0-9]))?\s?)(?:((?:9\d|[2-9])\d{3})-?(\d{4}))$", ErrorMessage = "Telefone do E-mail Inválido")]
        public int usuarioTelefone { get; set; }

        [Display(Name = "E-mail")]
        [Required(ErrorMessage = "E-mail deve ser informado!")]
        [RegularExpression(@"^[a-zA-Z]+(([\'\,\.\- ][a-zA-Z ])?[a-zA-Z]*)*\s+<(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})>$|^(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})$", ErrorMessage = "Formato do E-mail Inválido")]
        [Remote("EmailUnico", "Cadastrousuario", ErrorMessage = "e-mail já cadastrado")]
        [StringLength(50, ErrorMessage = "Senha deve ter no maximo maximo 50 caracteres!")]
        public string usuarioEmail { get; set; }

        [Display(Name = "Senha")]
        [Required(ErrorMessage = "Senha deve ser preenchida!")]
        [StringLength(25, MinimumLength = 4, ErrorMessage = "Senha deve ter entre 4 e 25 caracteres")]
        public string usuarioSenha { get; set; }

        [Display(Name = "Confirmar Senha")]
        [Required(ErrorMessage = "Confirmar Senha deve ser preenchida!")]
        [StringLength(25, MinimumLength = 4, ErrorMessage = "Senha deve ter entre 4 e 25 caracteres")]
        [Compare("Senha", ErrorMessage = "Senhas informadas não conferem")]
        public string usuarioConfirmarSenha { get; set; }

        [Display(Name = "Data de Nascimento")]
        [Required(ErrorMessage = "A data de nascimento é obrigatória!")]
        public DateTime usuarioDataNascimento { get; set; }

    }
}

WebPortal/Controllers/CadastroUsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;

namespace WebPortal.Controllers

{
    public class CadastroUsuarioController : Controller
    {
        public IActionResult Cadastro()
        {
            return View();
        }

        //public ActionResult EmailUnico(string Email)
        //{
        //    bool emailValido = false;

        //    emailValido = chamada a sua classe de verificacao de email com retorno(true / false)


        //    if (emailValido == true)
        //    {
        //        return Json(true, JsonRequestBehavior.AllowGet);
        //    }
        //    else
        //    {
        //        return Json(string.Format("E-mail '{0}' já esta cadastrado.", Email), JsonRequestBehavior.AllowGet);
        //    }
        //}


    }
}

WebPortal/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace WebPortal.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebPortal/Controllers/RecuperacaoSenhaController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebPortal.Controllers
{
    public class RecuperacaoSenhaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebPortal/Views/CadastroUsuario/Cadastro.cshtml
@{
    ViewData["Title"] = "Cadastro de Usuário";
}

<div class="row justify-content-center">
    <div class="col-6">
        <form style="background: #efefef" class="p-3 rounded">

            <div class="row justify-content-center mb-5">
                <div class="col">
                    <div class="col d-flex justify-content-center">
                        <img class="mb-4" src="~/lib/Themes/linkedin-png-icon-8.jpg" alt="" width="110" height="97">
                   </div>
                    <div class="col d-flex justify-content-center">
                        <h1 class="h3 mb-3 fw-normal text-center">Faça seu cadastro</h1>
                    </div>
                </div>
            </div>

            <div class="row pb-4 pt-5">
                <div class="col">
                    <input type="text" class="form-control" placeholder="Insira seu nome" aria-label="First name" required>
                </div>
                <div class="col">
                    <input type="text" class="form-control" placeholder="Insira seu sobrenome" aria-label="Last name" required>
                </div>
            </div>

            <div class="row pb-4">
                <div class="col">
                    <input type="email" class="form-control" placeholder="E-mail" aria-label="First name" required>
                </div>
                <div class="col">
                    <input type="text" class="form-control" placeholder="Celular" aria-label="Last name" required>
                </div>
            </div>

            <div class="row pb-4">
                <div class="col">
                    <input type="password" class="form-control" placeholder="Insira sua senha" min="4" maxlength="25" aria-label="First name" required>
                </div>
                <div class="col">
                    <input type="password" class="form-control" placeholder="Confirmar senha" min="4" maxlength="25" aria-label="Last name" required>
                </div>
            </div>

            <div class="row">
                <div class="col justify-content-center d-flex">
                    <input class="form-control" style="width: 250px" data-provide="datepicker" type="datetime" placeholder="Insira sua data de nascimento">
                 </div>
            </div> 

            <div class="row pt-5">
                <div class="col d-flex justify-content-center">
                    <button class="w-50 btn btn-lg btn-primary" type="submit">Entrar</button>
                </div>

                <p class="mt-1 d-flex justify-content-center pt-3">
                    <a asp-controller="Login" asp-action="Index">Não possui uma conta? Realize o cadastro</a>
                </p>

                <div class="row text-center">
                    <p class="mt-5 mb-3 text-muted">© Creation Vitae 2023</p>
                </div>
            </div>

        </form>
    </div>
</div>

WebPortal/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Login";
}

<div class="container">
    <div class="container-border m-auto">
        <main class="form-signin m-auto">
            <form>
                <img class="mb-4" src="~/lib/Themes/linkedin-png-icon-8.jpg" alt="" width="110" height="97">
                <h1 class="h3 mb-3 fw-normal text-center">Faça seu login</h1>
                <div class="form-floating">
                    <input type="email" class="form-control" id="txtEmail" placeholder="nome@exemplo.com">
                    <label for="floatingInput">Email</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control" id="txtSenha" placeholder="Senha">
                    <label for="floatingPassword">Senha</label>
                </div>
                <div class="checkbox mb-3 alinhamento">
                    <label>
                        <input type="checkbox" value="chkLembreDeMim"> Lembre de mim
                    </label>
                </div>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Entrar</button>
                <p class="mt-3 alinhamento">
                    <a asp-controller="RecuperacaoSenha" asp-action="Index">Esqueci minha senha</a>
                </p>
                <p class="mt-1">
                    <a asp-controller="CadastroUsuario" asp-action="Cadastro">Não possui uma conta? Realize o cadastro</a>
                </p>

                <p class="mt-5 mb-3 text-muted">© Creation Vitae 2023</p>
            </form>
        </main>
    </div>
</div>

WebPortal/Views/RecuperacaoSenha/Index.cshtml
@{
    ViewData["Title"] = "Cadastro de Usuário";
}

<h1>Alguma coisa toperson</h1>

WebPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Creation Vitae</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="~/WebPortal.styles.css" asp-append-version="true" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js">
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>